### ISSUE TITLE
Fetch product data from backend api

### ISSUE THREAD

**Issue by tyuLD** [we-we-Web/dongyi-web#6]

**Comment by Ateto1204** [comment]
Could you provide the details of the api workflow. The workflow mean how you fetch the api.

**Comment by tyuLD** [comment]
url: https://dongyi.hnd1.zeabur.app
fetch url -> 操作json檔 -> 把要的東西放到畫面上
error:  alert(error)
(我想不到還有什麼error)

**Comment by Ateto1204** [comment]
1. url 指的是路徑，比如說 https://demo.com/api/get/id?=1 之類的
2. 操作 json 跟放東西到畫面上應該是同一件事，然後東西是什麼要定義清楚
3. error 可能是 404 not found，去查一下 http code 然後跟後端討論一下，這個是他們要給的
